version: 2
updates:
- package-ecosystem: cargo
  directory: "/frontend"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: gomod
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
