#!/usr/bin/env bash
set -euo pipefail

mkdir -p bin
export GOBIN=$PWD/bin

go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.30.0
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

export PATH=$PWD/bin:$PATH

protoc -I. api/api.proto \
    --go_out=backend \
    --go-grpc_out=backend \
    --go_opt=paths=source_relative \
    --go-grpc_opt=paths=source_relative

sed -i -e '1h;2,$H;$!d;g' -re 's|// versions.+// source:|// source:|' backend/api/*.pb.go
