#!/usr/bin/env bash
set -euox pipefail

curl_retry() {
    curl -sSfL --retry 5 --retry-delay 3 "$@"
}

install_func() {
    curl_retry https://kn-openshift-serverless.apps.x.kube.direct/kn-linux-amd64.tar.gz -o- |
        tar xfz - -C /usr/local/bin
}

install_func
