[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
debug = 0
incremental = true
lto = true
opt-level = "z"
strip = "symbols"

[dependencies]
actix-rt = "2.8.0"
actix-web = "4.3.1"
actix-web-lab = "0.19.1"
askama = "0.12.0"
env_logger = "0.10.0"
log = "0.4.18"
