[package]
name = "function"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
actix-rt = "2.8.0"
log = "0.4.18"
env_logger = "0.10.0"
regex = "1.8.4"
tokio = "1.28.2"
actix-http = "3.3.1"

[dev-dependencies]
regex = "1.8.4"
tokio = "1.28.2"
actix-http = "3.3.1"
