---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-certificate
  namespace: kube-direct
spec:
  dnsNames:
  - kube.direct
  - www.kube.direct
  issuerRef:
    kind: ClusterIssuer
    name: issuer
  secretName: default-tls
