---
apiVersion: v1
imagePullSecrets:
- name: knative-dockercfg-tvhvd
kind: ServiceAccount
metadata:
  name: knative
  namespace: kube-direct
secrets:
- name: knative-dockercfg-tvhvd
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-rolebinding
  namespace: kube-direct
subjects:
- kind: ServiceAccount
  name: knative
roleRef:
  kind: Role
  name: knative-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knative-role
  namespace: kube-direct
rules:
  - verbs:
    - get
    - create
    - update
    apiGroups:
    - serving.knative.dev
    resources:
    - services
  - verbs:
    - get
    apiGroups:
    - serving.knative.dev
    resources:
    - routes
