---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-direct-backend-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-direct
roleRef:
  kind: ClusterRole
  name: kube-direct-backend-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-direct-backend-clusterrole
rules:
  - verbs:
    - list
    apiGroups:
    - ""
    resources:
    - nodes
