---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: main
    pipelinesascode.tekton.dev/task: git-clone
    pipelinesascode.tekton.dev/task-1: golangci-lint
  name: test
spec:
  params:
    - name: repo_url
      value: '{{ repo_url }}'
    - name: revision
      value: '{{ revision }}'

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

    - name: basic-auth
      secret:
        secretName: '{{ git_auth_secret }}'

  pipelineSpec:
    params:
      - name: repo_url
      - name: revision

    workspaces:
      - name: source
      - name: basic-auth

    tasks:
      - name: checkout
        taskRef:
          name: git-clone
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth

      - name: lint
        runAfter:
          - checkout
        taskRef:
          name: golangci-lint
        params:
          - name: package
            value: .
          - name: version
            value: v1.53.2
        workspaces:
          - name: source
            workspace: source
