---
name: deploy
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        function: [frontend, backend]
    steps:
      - uses: actions/checkout@v4
      - run: sudo .github/github-actions-setup
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cargo/registry
            ~/.cargo/git
            frontend/target
          key: ${{ runner.os }}-deploy-${{ matrix.function }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/go.sum') }}
      - name: Login to Quay.io
        run: docker login -u saschagrunert+github -p ${{ secrets.QUAY_PASSWORD }} quay.io
      - name: Prepare kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - run: sudo .github/github-actions-setup
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: wasm32-unknown-unknown
      - run: make deploy
        working-directory: ${{ matrix.function }}
      - uses: sigstore/cosign-installer@v3
      - run: .github/sign-image ${{ matrix.function }}
