---
name: deploy
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo .github/github-actions-setup
      - name: Login to Quay.io
        run: docker login -u saschagrunert+github -p ${{ secrets.QUAY_PASSWORD }} quay.io
      - name: Prepare kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - run: make deploy
        working-directory: frontend
