---
name: deploy
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        function: [frontend, backend]
    steps:
      - uses: actions/checkout@v3
      - run: sudo .github/github-actions-setup
      - name: Login to Quay.io
        run: docker login -u saschagrunert+github -p ${{ secrets.QUAY_PASSWORD }} quay.io
      - name: Prepare kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - run: make deploy
        working-directory: ${{ matrix.function }}
      - uses: sigstore/cosign-installer@v3
      - run: .github/sign-image ${{ matrix.function }}
