---
name: test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GOLANGCI_LINT_VERSION: v1.53.2

permissions: {}

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@v1.15.0
        with:
          config: .typos.toml

  frontend-func:
    name: frontend / func
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo .github/github-actions-setup
      - run: make build
        working-directory: frontend

  frontend-clippy:
    name: frontend / clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - name: Select Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
          components: clippy
      - name: Clippy
        run: cargo +nightly clippy --all-targets --all-features -- -D warnings
        working-directory: frontend

  frontend-rustfmt:
    name: frontend / rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Rustfmt
        run: cargo fmt && git diff --exit-code
        working-directory: frontend

  frontend-unit:
    name: frontend / unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Select Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Unit tests
        run: cargo test --no-fail-fast
        working-directory: frontend

  backend-func:
    name: backend / func
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo .github/github-actions-setup
      - run: make build
        working-directory: backend

  backend-lint:
    name: backend / lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo .github/github-actions-setup
      - uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: backend
