---
name: test
on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: "1.20"
  GOLANGCI_LINT_VERSION: v1.53.2

permissions: {}

jobs:
  func:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo .github/github-actions-setup
      - run: make build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
